# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

config.set('fonts.tabs', '8pt monospace')
config.set('fonts.statusbar', '8pt monospace')
config.set('fonts.completion.category', 'bold 8pt monospace')
config.set('fonts.completion.entry', '8pt monospace')
config.set('fonts.debug_console', '8pt monospace')
config.set('fonts.downloads', '8pt monospace')
config.set('fonts.hints', 'bold 8pt monospace')
config.set('fonts.keyhint', '8pt monospace')
config.set('fonts.messages.error', '8pt monospace')
config.set('fonts.messages.info', '8pt monospace')
config.set('fonts.messages.warning', '8pt monospace')
config.set('fonts.prompts', '8pt sans-serif')
config.set('url.searchengines', {"DEFAULT": "https://lite.duckduckgo.com/lite?q={}"})
config.set('url.start_pages', 'https://lite.duckduckgo.com/lite')
config.set('url.default_page', 'https://lite.duckduckgo.com/lite')
config.bind(',m', 'spawn mpv --ytdl-format=worst {url}')
config.bind(',M', 'hint links spawn mpv {hint-url}')
