# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

config.load_autoconfig()
config.set('url.searchengines', {"DEFAULT": "https://lite.duckduckgo.com/lite?q={}"})
config.set('url.start_pages', 'https://lite.duckduckgo.com/lite')
config.set('url.default_page', 'https://lite.duckduckgo.com/lite')
config.bind(',m', 'spawn mpv --ytdl-format=worst {url}')
config.bind(',M', 'hint links spawn mpv --ytdl-format=worst {hint-url}')
