# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

config.set('url.searchengines', {"DEFAULT": "https://lite.duckduckgo.com/lite?q={}"})
config.set('url.start_pages', 'about:blank')
config.set('url.default_page', 'about:blank')
config.bind(',m', 'spawn mpv --force-window=yes --ytdl-format=bestaudio {url}')
config.bind(',M', 'hint links spawn mpv --force-window=yes --ytdl-format=bestaudio {hint-url}')
